#ifndef BLADE_ATA_MODE_A_CONFIG_H
#define BLADE_ATA_MODE_A_CONFIG_H

#define BLADE_ATA_MODE_A_CHANNELIZER_RATE 1 // [1, 4]; <= 1 mitigates the channlisation

#define BLADE_ATA_MODE_A_INPUT_NANT 20
#define BLADE_ATA_MODE_A_INPUT_NCOMPLEX_BYTES 2

#define BLADE_ATA_MODE_A_ANT_NCHAN 192
#define BLADE_ATA_MODE_A_NTIME 8192
#define BLADE_ATA_MODE_A_NPOL 2

#define BLADE_ATA_MODE_A_OUTPUT_NBEAM 2
#define BLADE_ATA_MODE_A_INTEGRATION_SIZE 1
#define BLADE_ATA_MODE_A_OUTPUT_NPOL 2

#define BLADE_ATA_MODE_A_OUTPUT_N_BYTES 4
#define BLADE_ATA_MODE_A_OUTPUT_ELEMENT_T F32


#define BLADE_ATA_MODE_A_OUTPUT_MEMCPY2D_PAD 0 // zero makes memcpy2D effectively 1D
#define BLADE_ATA_MODE_A_OUTPUT_MEMCPY2D_WIDTH 8192

#define BLADE_ATA_MODE_A_OUTPUT_MEMCPY2D_DPITCH (BLADE_ATA_MODE_A_OUTPUT_MEMCPY2D_WIDTH+BLADE_ATA_MODE_A_OUTPUT_MEMCPY2D_PAD)

#define BLADE_ATA_MODE_A_OUTPUT_DATA_SIZE (BLADE_ATA_MODE_A_OUTPUT_NBEAM *\
                               BLADE_ATA_MODE_A_ANT_NCHAN *\
                               BLADE_ATA_MODE_A_NTIME *\
                               BLADE_ATA_MODE_A_OUTPUT_NPOL *\
                               BLADE_ATA_MODE_A_OUTPUT_N_BYTES /\
															 BLADE_ATA_MODE_A_INTEGRATION_SIZE)

// #define BLADE_ATA_MODE_A_DATA_SIZE ((BLADE_ATA_MODE_A_OUTPUT_DATA_SIZE/BLADE_ATA_MODE_A_OUTPUT_MEMCPY2D_WIDTH)*BLADE_ATA_MODE_A_OUTPUT_MEMCPY2D_DPITCH)
#define BLADE_ATA_MODE_A_DATA_SIZE BLADE_ATA_MODE_A_OUTPUT_DATA_SIZE

#endif